korean_to_english = {
    "서울": "Seoul", "서울특별시": "Seoul", "서울시": "Seoul",
    "부산": "Busan", "부산광역시": "Busan", "부산시": "Busan",
    "대구": "Daegu", "대구광역시": "Daegu", "대구시": "Daegu",
    "인천": "Incheon", "인천광역시": "Incheon", "인천시": "Incheon",
    "광주": "Gwangju", "광주광역시": "Gwangju", "광주시": "Gwangju",
    "대전": "Daejeon", "대전광역시": "Daejeon", "대전시": "Daejeon",
    "울산": "Ulsan", "울산광역시": "Ulsan", "울산시": "Ulsan",
    "세종": "Sejong", "세종특별자치시": "Sejong", "세종시": "Sejong",
    "제주": "Jeju", "제주특별자치도": "Jeju", "제주도": "Jeju",
    "강남": "Gangnam", "강남구": "Gangnam",
    "강동": "Gangdong", "강동구": "Gangdong",
    "강서": "Gangseo", "강서구": "Gangseo",
    "관악": "Gwanak", "관악구": "Gwanak",
    "광진": "Gwangjin", "광진구": "Gwangjin",
    "구로": "Guro", "구로구": "Guro",
    "금천": "Geumcheon", "금천구": "Geumcheon",
    "노원": "Nowon", "노원구": "Nowon",
    "도봉": "Dobong", "도봉구": "Dobong",
    "동대문": "Dongdaemun", "동대문구": "Dongdaemun",
    "동작": "Dongjak", "동작구": "Dongjak",
    "마포": "Mapo", "마포구": "Mapo",
    "서대문": "Seodaemun", "서대문구": "Seodaemun",
    "서초": "Seocho", "서초구": "Seocho",
    "성동": "Seongdong", "성동구": "Seongdong",
    "성북": "Seongbuk", "성북구": "Seongbuk",
    "송파": "Songpa", "송파구": "Songpa",
    "양천": "Yangcheon", "양천구": "Yangcheon",
    "영등포": "Yeongdeungpo", "영등포구": "Yeongdeungpo",
    "용산": "Yongsan", "용산구": "Yongsan",
    "은평": "Eunpyeong", "은평구": "Eunpyeong",
    "종로": "Jongno", "종로구": "Jongno",
    "중구": "Jung-gu",    "중랑": "Jungnang", "중랑구": "Jungnang",
    "수원": "Suwon", "수원시": "Suwon",
    "성남": "Seongnam", "성남시": "Seongnam",
    "고양": "Goyang", "고양시": "Goyang",
    "용인": "Yongin", "용인시": "Yongin",
    "부천": "Bucheon", "부천시": "Bucheon",
    "안산": "Ansan", "안산시": "Ansan",
    "안양": "Anyang", "안양시": "Anyang",
    "남양주": "Namyangju", "남양주시": "Namyangju",
    "화성": "Hwaseong", "화성시": "Hwaseong",
    "평택": "Pyeongtaek", "평택시": "Pyeongtaek",
    "의정부": "Uijeongbu", "의정부시": "Uijeongbu",
    "시흥": "Siheung", "시흥시": "Siheung",
    "파주": "Paju", "파주시": "Paju",
    "광명": "Gwangmyeong", "광명시": "Gwangmyeong",
    "김포": "Gimpo", "김포시": "Gimpo",
    "군포": "Gunpo", "군포시": "Gunpo",
    "광주": "Gwangju", "경기광주": "Gwangju-si",    "이천": "Icheon", "이천시": "Icheon",
    "양주": "Yangju", "양주시": "Yangju",
    "오산": "Osan", "오산시": "Osan",
    "구리": "Guri", "구리시": "Guri",
    "안성": "Anseong", "안성시": "Anseong",
    "포천": "Pocheon", "포천시": "Pocheon",
    "의왕": "Uiwang", "의왕시": "Uiwang",
    "하남": "Hanam", "하남시": "Hanam",
    "여주": "Yeoju", "여주시": "Yeoju",
    "동두천": "Dongducheon", "동두천시": "Dongducheon",
    "과천": "Gwacheon", "과천시": "Gwacheon",
    "가평": "Gapyeong", "가평군": "Gapyeong",
    "양평": "Yangpyeong", "양평군": "Yangpyeong",
    "연천": "Yeoncheon", "연천군": "Yeoncheon",
    "해운대": "Haeundae",
    "홍대": "Hongdae",
    "신촌": "Sinchon",
    "여의도": "Yeouido",
    "분당": "Bundang",
    "일산": "Ilsan",
    "판교": "Pangyo",
    "동탄": "Dongtan",
    "광교": "Gwanggyo",
    "송도": "Songdo",
    "청라": "Cheongna",
    "서면": "Seomyeon",    "남포동": "Nampo-dong",
    "동성로": "Dongseong-ro",    "둔산동": "Dunsan-dong",    "상무지구": "Sangmu",    "센텀": "Centum City",
    "울릉도": "Ulleungdo",
    "독도": "Dokdo",
    "춘천": "Chuncheon", "강릉": "Gangneung", "원주": "Wonju", "속초": "Sokcho", "동해": "Donghae", "태백": "Taebaek",
    "삼척": "Samcheok", "홍천": "Hongcheon", "횡성": "Hoengseong", "영월": "Yeongwol", "평창": "Pyeongchang",
    "정선": "Jeongseon", "철원": "Cheorwon", "화천": "Hwacheon", "양구": "Yanggu", "인제": "Inje", "고성": "Goseong", "양양": "Yangyang",
    "청주": "Cheongju", "충주": "Chungju", "제천": "Jecheon", "천안": "Cheonan", "공주": "Gongju", "보령": "Boryeong",
    "아산": "Asan", "서산": "Seosan", "논산": "Nonsan", "계룡": "Gyeryong", "당진": "Dangjin", "금산": "Geumsan",
    "부여": "Buyeo", "서천": "Seocheon", "청양": "Cheongyang", "홍성": "Hongseong", "예산": "Yesan", "태안": "Taean",
    "단양": "Danyang", "영동": "Yeongdong", "보은": "Boeun", "옥천": "Okcheon", "음성": "Eumseong", "진천": "Jincheon", "괴산": "Goesan", "증평": "Jeungpyeong",
    "전주": "Jeonju", "군산": "Gunsan", "익산": "Iksan", "정읍": "Jeongeup", "남원": "Namwon", "김제": "Gimje",
    "목포": "Mokpo", "여수": "Yeosu", "순천": "Suncheon", "나주": "Naju", "광양": "Gwangyang", "담양": "Damyang",
    "곡성": "Gokseong", "구례": "Gurye", "고흥": "Goheung", "보성": "Boseong", "화순": "Hwasun", "장흥": "Jangheung",
    "강진": "Gangjin", "해남": "Haenam", "영암": "Yeongam", "무안": "Muan", "함평": "Hampyeong", "영광": "Yeonggwang",
    "장성": "Jangseong", "완도": "Wando", "진도": "Jindo", "신안": "Sinan", "완주": "Wanju", "진안": "Jinan", "무주": "Muju",
    "장수": "Jangsu", "임실": "Imsil", "순창": "Sunchang", "고창": "Gochang", "부안": "Buan",
    "포항": "Pohang", "경주": "Gyeongju", "김천": "Gimcheon", "안동": "Andong", "구미": "Gumi", "영주": "Yeongju",
    "영천": "Yeongcheon", "상주": "Sangju", "문경": "Mungyeong", "경산": "Gyeongsan", "창원": "Changwon", "진주": "Jinju",
    "통영": "Tongyeong", "사천": "Sacheon", "김해": "Gimhae", "밀양": "Miryang", "거제": "Geoje", "양산": "Yangsan",
    "의령": "Uiryeong", "함안": "Haman", "창녕": "Changnyeong", "고성": "Goseong", "남해": "Namhae", "하동": "Hadong",
    "산청": "Sancheong", "함양": "Hamyang", "거창": "Geochang", "합천": "Hapcheon", "군위": "Gunwi", "의성": "Uiseong",
    "청송": "Cheongsong", "영양": "Yeongyang", "영덕": "Yeongdeok", "청도": "Cheongdo", "고령": "Goryeong", "성주": "Seongju",
    "칠곡": "Chilgok", "예천": "Yecheon", "봉화": "Bonghwa", "울진": "Uljin"
}
def get_english_name(location_kr: str) -> str:
    cleaned_loc = location_kr.strip()
    if cleaned_loc in korean_to_english:
        return korean_to_english[cleaned_loc]
    for suffix in ["특별시", "광역시", "특별자치시", "특별자치도", "시", "군", "구", "동", "읍", "면"]:
        if cleaned_loc.endswith(suffix):
            prefix = cleaned_loc[:-len(suffix)]
            if prefix in korean_to_english:
                return korean_to_english[prefix]
    return location_kr
english_to_korean = {v: k for k, v in korean_to_english.items()}
english_to_korean.update({
    "Seoul": "서울",
    "Busan": "부산",
    "Daegu": "대구",
    "Incheon": "인천",
    "Gwangju": "광주",
    "Daejeon": "대전",
    "Ulsan": "울산",
    "Sejong": "세종",
    "Jeju": "제주",
    "Gangnam": "강남구",
    "Haeundae": "해운대",
    "Hongdae": "홍대",
    "Yeouido": "여의도"
})
def get_korean_name(location_en: str) -> str:
    if location_en in english_to_korean:
        return english_to_korean[location_en]
    for k, v in english_to_korean.items():
        if k.lower() == location_en.lower():
            return v
    return location_en